# Generated by Django 3.1.3 on 2020-11-28 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ('-add_date',)},
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='body',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='created_by',
        ),
        migrations.AddField(
            model_name='tweet',
            name='add_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='add date'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='content',
            field=models.TextField(default='', verbose_name='Tweet'),
            preserve_default=False,
        ),
    ]
